fix unsigned long long *:1
lol

Missing type converters:
unsigned long long *:1
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1